on:
  workflow_dispatch:
    inputs:
      browser:
        type: choice
        description: Which browser to test
        required: true
        options:
          - remote
jobs:
  memos-automation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      - name: Set envs variables
        run: echo "${{ secrets.ENV_FILE }}" > ./config/.docker.env
      - name: Build project
        run: docker-compose build
      - name: Services Up
        run: |
          docker-compose --env-file ./config/.docker.env up -d
      - name: Check envs
        run: cat ./config/.docker.env
      - name: Wait for services
        run: sh wait.sh
      - name: Run tests
        run: docker-compose exec -T pytest-memos pytest --alluredir=./report
      - name: Generate report
        run: docker-compose exec -T pytest-memos allure generate ./report -o ./html
