on:
  workflow_dispatch:
    inputs:
      browser:
        type: choice
        description: Which browser to test
        required: true
        options:
          - remote
jobs:
  memos-automation:
    env:
      BROWSER: "remote"
      BASE_URL: "http://memos:5230"
      SELENIUM_HUB_HOST: "http://selenium-hub:4444/wd/hub"
      ADMIN_USERNAME: ${{secrets.ADMIN_USERNAME}}
      ADMIN_PASSWORD: ${{secrets.ADMIN_USERNAME}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      - name: Build project
        run: docker-compose build
      - name: Run tests
        run: docker-compose pytest-memos exec pytest --alluredir=./report
      - name: Generate report
        run: allure generate ./report -o ./html
